#!/usr/bin/env bash
# counts to 10 and says Hi at 9
COUNT=0
while [ $COUNT -lt 10 ]
do
	if [ $COUNT = 8 ]
	then
		echo "hi"
		COUNT=$((COUNT+1))
	else
		echo "Holberton School"
		COUNT=$((COUNT+1))
	fi
done
