#!/usr/bin/env bash
# counts to 20 and shows you bad luck numbers from around the world
ct=1
while [ $ct -lt 21 ]
do
	case $ct in
		5) echo "bad luck from China"
			echo $ct
			ct=$((ct+1));;
		10) echo "bad luck from Japan"
			echo $ct
			ct=$((ct+1));;
		18) echo "bad luck from Italy"
			echo $ct
			ct=$((ct+1));;
		*) echo $ct
			ct=$((ct+1));;
	esac
done
